version: "3.8"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: todo_app
    ports:
      - "5435:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  backend:
    build:
      context: ./todo-app-backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://your_username:your_password@postgres/todo_app
    depends_on:
      - postgres
  frontend:
    build:
      context: ././todo-app-frontened
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
volumes:
  postgres-data:
