version: "3.8"
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  backend:
    build:
      context: ./todo-app-backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://youruser:yourpassword@postgres/yourdb
    depends_on:
      - postgres
  frontend:
    build:
      context: ././todo-app-frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
volumes:
  postgres-data:
